### ISSUE TITLE
How to visualize the data

### ISSUE THREAD

**Issue by BenRoe** [nobodyinperson/co2monitor#17] opened 2017-03-08 16:41 UTC
An quick advise how to visualize the data to a graph?

**Comment by nobodyinperson** [comment] 2017-03-08 17:22
Oh yes, there is a hacky [R script](https://github.com/nobodyinperson/co2monitor/blob/master/usr/share/doc/co2monitor/examples/plot.R) at `/usr/share/doc/co2monitor/examples/plot.R`.

In the next release I will include a desktop file.

**Comment by nobodyinperson** [comment] 2017-03-08 21:26
Version [v0.0.12](https://github.com/nobodyinperson/co2monitor/releases/tag/v0.0.12) ships with a menu .desktop file that starts the plotting script `/usr/share/doc/co2monitor/examples/plot.R` which continually shows a graph of the latest data.

**Comment by BenRoe** [comment] 2017-03-08 22:47
If i open co2monitor on desktop, i get an error 'folder not found' or something similar.

**Comment by nobodyinperson** [comment] 2017-03-09 08:03
What do you mean by "co2monitor"?

- the menu icon
- the unfinished gui `/usr/bin/co2monitor`

Please try

`/usr/share/doc/co2monitor/examples/plot.R` in the Terminal and post what it says.

**Comment by BenRoe** [comment] 2017-03-14 00:44
If i click the co2monitor icon in the start menu, an error "Failed to change to directory (No such file or directory)".
If i use ``/usr/share/doc/co2monitor/examples/plot.R`` it show the graph. Thanks for the hint.

**Comment by nobodyinperson** [comment] 2017-03-14 06:50
Okay, for whatever reason, I left the `Path` field empty in [the .desktop file](https://github.com/nobodyinperson/co2monitor/blob/master/usr/share/applications/co2monitor.desktop). I am using Xubuntu 16.04, obviously XFCE4 doesn't bother the missing `Path`, because for me it works. Could you please:

- tell what desktop environment you use
- remove the `Path` field from the file `/usr/share/applications/co2monitor.desktop` (with root privileges)
- try if it works now
- If not, set some arbitrary path, e.g. `Path=/` and retry

Thanks!

nobodyinperson

**Comment by BenRoe** [comment] 2017-03-14 22:25
I use Raspbian Jessie.
If i set the ``Path=/`` or remove it and click on the desktop icon, the program starts for a second and close it.

**Comment by nobodyinperson** [comment] 2017-03-15 21:10
Hm... l can not reproduce this on my Raspbian jessie... When I click the co2monitor desktop-file, the graph shows as expected. The only thing that I can imagine goes wrong for you, is that either:

- you have no `.csv` data files under `/var/lib/co2monitor/data` or
- one of your `.csv` data files under `/var/lib/co2monitor/data` is somehow broken (only the header present, not real csv format, etc...)

and thus the `plot.R` crashes. Try investigating your data or just remove everything (`rm /var/lib/co2monitor/data/*.csv`) if you don't mind losing your CO2 data and then plug the device back in to produce new data files.

**Comment by nobodyinperson** [comment] 2017-08-01 13:06
@BenRoe In case you are still interested in **co2monitor**, I migrated it to [GitLab.com](https://gitlab.com/nobodyinperson/co2monitor). This same issue is present there, see [here](https://gitlab.com/nobodyinperson/co2monitor/issues/17).

I will thus close this issue.

**Closed as completed by nobodyinperson** 2017-08-01 13:06 UTC
